# Contributors
# ---------------------------
# En-Ho Shen <enhoshen@gmail.com>, 2026

from video_concat.lib import Interactive
import argparse


def create_parser():
    parser = argparse.ArgumentParser(
        prog="VideoConcat",
        description=(
            "Produce chapter metadata and text from video filenames "
            "generated by Shadowplay and processed by LosslessCut. "
            "This script helps in creating chapter information for video files."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "-s",
        "--standby",
        action="store_true",
        help="Don't read files under base during setup",
    )
    parser.add_argument(
        "-b",
        "--base",
        action="store",
        help="The base directory containing input video files.",
    )
    parser.add_argument(
        "-o",
        "--out_dir",
        action="store",
        help="The directory to save output files.",
    )
    parser.add_argument(
        "-c",
        "--compress",
        action="store_true",
        help="Enable HEVC NVENC compression.",
    )
    parser.add_argument(
        "--bitrate",
        action="store",
        default=4,
        help="Compression bitrate (default: 4).",
    )
    parser.add_argument(
        "-m",
        "--move",
        action="store_true",
        default=False,
        help="If specified, move videos and start processing.",
    )
    parser.add_argument(
        "-cf",
        "--comment-file",
        action="store",
        help="Path to the YAML comment file.",
    )
    return parser


if __name__ == "__main__":
    parser = create_parser()
    args = parser.parse_args()
    interactive = Interactive(args)
    if args.move:
        interactive.move()
        interactive.run()
        exit(0)

    read = interactive.read
    reread = interactive.reread
    copy = interactive.copy
    move = interactive.move
    run = interactive.run
    compress = interactive.compress_all
